version: '3.4'

services:
  notatnik.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ./cert/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./cert/Https:/root/.aspnet/https:ro