version: '3'
networks:
    paczkomat:
services:
  notatnik.server:
    build:
      context: .
      dockerfile: Notatnik/Server/Dockerfile
    ports:
        - "5000:443"
    depends_on:
        - sql
    command: ["dotnet", "ef", "database update"]
    networks:
      - paczkomat
  sql:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        networks:
            - paczkomat


